apiVersion: v1
kind: Service
metadata:
  name: login-app
spec:
  selector:
    app: login-app
  type: ClusterIP
  ports:
    - port: 8005
      targetPort: 8005
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  labels:
    app: login-app
spec:
  selector:
    matchLabels:
      app: login-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
        - name: login-app
          image: login-app:3
          ports:
            - containerPort: 8005
          env: # Setting Environmental Variables
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_DATABASE
              value: testDB
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
